# Generated by Django 5.2.3 on 2025-06-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabularies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='dictionary',
            new_name='vocabulary',
        ),
    ]
